/**
 * gen_seed_sql.js — generate a plain SQL upsert file from the scenario JSONs.
 * ---------------------------------------------------------------------------
 * Offline alternative to seed_scenarios.js for environments where Node cannot
 * reach Supabase directly (e.g. a corporate network with TLS inspection).
 * Reads every supabase/premium/scenarios/*.json and writes
 * supabase/premium/seed_scenarios.generated.sql — paste that into the Supabase
 * SQL Editor and Run. Produces the SAME rows the Node seeder would upsert:
 *   teaser  = public-safe teaser object
 *   content = { start, nodes } (PROTECTED body; lives only in the DB)
 *
 * No network, no secret key. Usage:
 *   node supabase/premium/gen_seed_sql.js
 */

'use strict';

const fs = require('fs');
const path = require('path');

// Escape a JS string for a single-quoted Postgres string literal.
function sqlStr(s) {
  return "'" + String(s).replace(/'/g, "''") + "'";
}

// Escape a JSON object for a single-quoted Postgres jsonb literal.
function sqlJson(obj) {
  return "'" + JSON.stringify(obj).replace(/'/g, "''") + "'::jsonb";
}

function main() {
  const dir = path.join(__dirname, 'scenarios');
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.json')).sort();
  if (!files.length) { console.error('No scenario JSON files found.'); process.exit(1); }

  const lines = [
    '-- OfferReady — generated scenario seed (offline).',
    '-- Generated by supabase/premium/gen_seed_sql.js. Do not edit by hand.',
    '-- Paste into the Supabase SQL Editor and Run. Idempotent (upsert by slug).',
    '',
    'begin;',
    '',
  ];

  for (const file of files) {
    const raw = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8'));
    const teaser = raw.teaser || {};
    const content = { start: raw.start, nodes: raw.nodes };
    lines.push(
      'insert into public.premium_content',
      '  (slug, title, category, required_entitlement, teaser, content, published)',
      'values (',
      '  ' + sqlStr(raw.slug) + ',',
      '  ' + sqlStr(raw.title) + ',',
      '  ' + (raw.category ? sqlStr(raw.category) : 'null') + ',',
      '  ' + sqlStr(raw.required_entitlement) + ',',
      '  ' + sqlJson(teaser) + ',',
      '  ' + sqlJson(content) + ',',
      '  true',
      ')',
      'on conflict (slug) do update set',
      '  title = excluded.title,',
      '  category = excluded.category,',
      '  required_entitlement = excluded.required_entitlement,',
      '  teaser = excluded.teaser,',
      '  content = excluded.content,',
      '  published = excluded.published;',
      '',
    );
  }

  lines.push('commit;', '');

  const outPath = path.join(__dirname, 'seed_scenarios.generated.sql');
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
  console.log('Wrote ' + outPath + ' (' + files.length + ' scenarios).');
}

main();
